---
services:
  www:
    image: nginx:1.22
    container_name: www
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./conf-nginx:/etc/nginx/conf.d
      - ./site:/usr/share/nginx/html
    environment:
      TZ: Europe/Paris
    depends_on:
      - php
    restart: always

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./site:/var/www/html
    environment:
      TZ: Europe/Paris
    restart: always
