---
services:
  www:
    image: ${NGINX_IMAGE_NAME}:${NGINX_IMAGE_VERSION}
    container_name: www
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./conf-nginx:/etc/nginx/conf.d
      - ./site:/usr/share/nginx/html
    environment:
      TZ: Europe/Paris
    depends_on:
      - php
    restart: always

  php:
    image: ${PHP_IMAGE_NAME}:${PHP_IMAGE_VERSION}
    container_name: php
    volumes:
      - ./site:/var/www/html
    env_file:
      - tz_file
    restart: always

  db:
    image: ${MARIADB_IMAGE_NAME}:${MARIADB_IMAGE_VERSION}
    container_name: db
    volumes:
      - datadir:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    restart: always

volumes:
  datadir:
